/**
 * 언어에 무관한 사실만 여기 둔다. `title`·`summary`는 `text.{ko,en}.ts`,
 * 긴 설명은 `src/content/projects/{ko,en}/<slug>.mdx` 본문에 있다.
 */

export const PROJECTS = [
  {
    slug: 'rhseung-me',
    domain: 'web',
    stack: ['astro', 'react', 'tailwindcss', 'typescript'],
    start: '2026-08',
    status: 'active',
    pinned: true,
    links: { repo: 'https://github.com/rhseung/rhseung' },
  },
  {
    slug: 'campass',
    domain: 'web',
    stack: ['react', 'tailwindcss', 'tanstack-router', 'vite', 'bun', 'typescript'],
    start: '2024-11',
    end: '2024-11',
    status: 'shipped',
    links: { demo: 'https://campass-fe.vercel.app/' },
  },
  {
    slug: 'pingpong',
    domain: 'graphics',
    stack: ['c++'],
    start: '2024-10',
    end: '2025-01',
    status: 'shipped',
    links: { repo: 'https://github.com/studio-void/hinguri-pingpong' },
  },
  {
    slug: 'neat',
    domain: 'systems',
    stack: ['java', 'swing'],
    start: '2024-09',
    status: 'active',
    links: { repo: 'https://github.com/gsa-projects/artificial-aquarium' },
  },
  {
    slug: 'glance',
    domain: 'systems',
    stack: ['java', 'kotlin'],
    start: '2024-06',
    status: 'active',
    links: {
      repo: 'https://github.com/rhseung-mods/glance',
      package: 'https://modrinth.com/mod/glance',
    },
  },
  {
    slug: 'fliggle',
    domain: 'web',
    stack: ['dart', 'flutter', 'nest.js', 'prisma', 'figma'],
    start: '2024-05',
    end: '2024-07',
    status: 'shipped',
    links: { repo: 'https://github.com/rhseung/toonflix-fe' },
  },
  {
    slug: 'idp',
    domain: 'web',
    stack: ['react', 'typescript', 'tanstack-router', 'tailwindcss', 'openapi-typescript', 'vite'],
    start: '2024-03',
    end: '2024-08',
    status: 'shipped',
    links: { repo: 'https://github.com/gsainfoteam/idp-fe', demo: 'https://idp.gistory.me' },
  },
  {
    slug: 'particles',
    domain: 'graphics',
    stack: ['c++'],
    start: '2024-03',
    end: '2024-11',
    status: 'shipped',
    links: { repo: 'https://github.com/rhseung/particles' },
  },
  {
    slug: 'pattern',
    domain: 'systems',
    stack: ['npm', 'typescript'],
    start: '2024-02',
    end: '2024-05',
    status: 'shipped',
    links: {
      repo: 'https://github.com/essentialib/pattern',
      package: 'https://www.npmjs.com/package/@essentialib/pattern',
    },
  },
  {
    slug: 'datetime',
    domain: 'systems',
    stack: ['npm', 'typescript'],
    start: '2024-01',
    end: '2024-04',
    status: 'shipped',
    links: {
      repo: 'https://github.com/essentialib/datetime',
      package: 'https://www.npmjs.com/package/@essentialib/datetime',
    },
  },
  {
    slug: 'siunits',
    domain: 'systems',
    stack: ['python'],
    start: '2023-12',
    status: 'active',
    links: {
      repo: 'https://github.com/rhseung/siunits',
      package: 'https://pypi.org/project/rhseung.units/',
    },
  },
  {
    slug: 'gsa-bot',
    domain: 'backend',
    stack: ['node.js', 'npm', 'typescript', 'javascript'],
    start: '2023-09',
    end: '2024-02',
    status: 'active',
    links: { repo: 'https://github.com/GSAStudentCouncil/gsa-bot' },
  },
  {
    slug: 'yolov3',
    domain: 'graphics',
    stack: ['python', 'pytorch'],
    start: '2023-03',
    end: '2023-11',
    status: 'shipped',
    links: { repo: 'https://github.com/gsa-projects/2023-rne' },
  },
] as const;

export type ProjectSlug = (typeof PROJECTS)[number]['slug'];
