import type { ProjectData } from './types';

// 언어 무관한 사실만. 번역문은 `text.{ko,en}.ts`.

export const PROJECTS = [
  {
    slug: 'rhseung-me',
    domain: 'web',
    stack: ['Astro', 'React', 'Tailwind CSS', 'TypeScript'],
    start: '2026-08',
    status: 'active',
    pinned: true,
    links: { repo: 'https://github.com/rhseung/rhseung' },
  },
  {
    slug: 'campass',
    domain: 'web',
    stack: ['React', 'Tailwind CSS', 'TanStack Router', 'Vite', 'Bun', 'TypeScript'],
    start: '2024-11',
    end: '2024-11',
    status: 'shipped',
    links: { demo: 'https://campass-fe.vercel.app/' },
  },
  {
    slug: 'pingpong',
    domain: 'graphics',
    stack: ['C++'],
    start: '2024-10',
    end: '2025-01',
    status: 'shipped',
    links: { repo: 'https://github.com/studio-void/hinguri-pingpong' },
  },
  {
    slug: 'neat',
    domain: 'systems',
    stack: ['Java', 'Swing'],
    start: '2024-09',
    status: 'active',
    links: { repo: 'https://github.com/gsa-projects/artificial-aquarium' },
  },
  {
    slug: 'glance',
    domain: 'systems',
    stack: ['Java', 'Kotlin'],
    start: '2024-06',
    status: 'active',
    links: {
      repo: 'https://github.com/rhseung-mods/glance',
      package: 'https://modrinth.com/mod/glance',
    },
  },
  {
    slug: 'fliggle',
    domain: 'web',
    stack: ['Dart', 'Flutter', 'Nest.js', 'Prisma', 'Figma'],
    start: '2024-05',
    end: '2024-07',
    status: 'shipped',
    links: { repo: 'https://github.com/rhseung/toonflix-fe' },
  },
  {
    slug: 'idp',
    domain: 'web',
    stack: ['React', 'TypeScript', 'TanStack Router', 'Tailwind CSS', 'OpenAPI TypeScript', 'Vite'],
    start: '2024-03',
    end: '2024-08',
    status: 'shipped',
    links: { repo: 'https://github.com/gsainfoteam/idp-fe', demo: 'https://idp.gistory.me' },
  },
  {
    slug: 'particles',
    domain: 'graphics',
    stack: ['C++'],
    start: '2024-03',
    end: '2024-11',
    status: 'shipped',
    links: { repo: 'https://github.com/rhseung/particles' },
  },
  {
    slug: 'pattern',
    domain: 'systems',
    stack: ['npm', 'TypeScript'],
    start: '2024-02',
    end: '2024-05',
    status: 'shipped',
    links: {
      repo: 'https://github.com/essentialib/pattern',
      package: 'https://www.npmjs.com/package/@essentialib/pattern',
    },
  },
  {
    slug: 'datetime',
    domain: 'systems',
    stack: ['npm', 'TypeScript'],
    start: '2024-01',
    end: '2024-04',
    status: 'shipped',
    links: {
      repo: 'https://github.com/essentialib/datetime',
      package: 'https://www.npmjs.com/package/@essentialib/datetime',
    },
  },
  {
    slug: 'siunits',
    domain: 'systems',
    stack: ['Python'],
    start: '2023-12',
    status: 'active',
    links: {
      repo: 'https://github.com/rhseung/siunits',
      package: 'https://pypi.org/project/rhseung.units/',
    },
  },
  {
    slug: 'gsa-bot',
    domain: 'backend',
    stack: ['Node.js', 'npm', 'TypeScript', 'JavaScript'],
    start: '2023-09',
    end: '2024-02',
    status: 'active',
    links: { repo: 'https://github.com/GSAStudentCouncil/gsa-bot' },
  },
  {
    slug: 'yolov3',
    domain: 'graphics',
    stack: ['Python', 'PyTorch'],
    start: '2023-03',
    end: '2023-11',
    status: 'shipped',
    links: { repo: 'https://github.com/gsa-projects/2023-rne' },
  },
] as const satisfies readonly ProjectData[];

export type ProjectSlug = (typeof PROJECTS)[number]['slug'];
