// 생성물입니다. `bun run gen:favicons` 로 다시 굽습니다.
export const FAVICON_HOSTS = new Set([
  '1password.com',
  'adguard.com',
  'adoptium.net',
  'agent-browser.dev',
  'brew.sh',
  'bun.com',
  'chromewebstore.google.com',
  'claude.ai',
  'claude.com',
  'code.claude.com',
  'developer.1password.com',
  'docs.astral.sh',
  'docs.claude.com',
  'emilkowal.ski',
  'flutter.dev',
  'github.com',
  'mise.jdx.dev',
  'nodejs.org',
  'pyrefly.org',
  'pytorch.kr',
  'www.google.com',
  'www.python.org',
  'www.raycast.com',
  'www.rust-lang.org',
]);
