// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "blog": {
    "detail": {
      "back": "글 목록"
    },
    "empty": {
      "description": "곧 채웁니다.",
      "title": "아직 쓴 글이 없습니다"
    },
    "item": {
      "writtenIn": "글이 쓰인 언어"
    },
    "page": {
      "description": "요즘 파고 있는 것들. 글은 쓴 언어 그대로 둡니다.",
      "title": "글"
    }
  },
  "common": {
    "actions": {
      "switchLanguage": "언어 바꾸기",
      "toggleTheme": "테마 바꾸기"
    },
    "footer": {
      "email": "이메일"
    },
    "nav": {
      "blog": "글",
      "career": "이력",
      "home": "홈",
      "label": "주요 메뉴",
      "menu": "메뉴",
      "projects": "프로젝트",
      "research": "연구"
    },
    "notFound": {
      "action": "홈으로",
      "description": "주소를 다시 확인해 주세요.",
      "title": "페이지를 찾을 수 없습니다"
    }
  },
  "home": {
    "hero": {
      "projects": "프로젝트 보기",
      "resume": "이력서 보기"
    },
    "sections": {
      "about": "더 자세히 →",
      "intro": "소개",
      "posts": "최근 글",
      "projects": "골라둔 것"
    }
  },
  "projects": {
    "detail": {
      "back": "프로젝트 목록"
    },
    "domain": {
      "backend": "백엔드",
      "graphics": "그래픽스",
      "systems": "시스템",
      "web": "웹"
    },
    "empty": {
      "description": "다른 분야를 골라보세요.",
      "title": "해당하는 프로젝트가 없습니다"
    },
    "filter": {
      "label": "분야로 좁히기",
      "reset": "필터 지우기",
      "results": "{{count}}개",
      "stack": "기술로 좁히기"
    },
    "links": {
      "demo": "데모",
      "package": "패키지",
      "paper": "논문",
      "post": "관련 글",
      "repo": "저장소"
    },
    "page": {
      "description": "직접 만든 것들. 분야로 좁혀서 볼 수 있습니다.",
      "title": "프로젝트"
    },
    "period": {
      "ongoing": "현재"
    },
    "search": {
      "clear": "검색어 지우기",
      "label": "프로젝트 검색",
      "placeholder": "제목·설명·기술로 검색"
    },
    "status": {
      "active": "진행 중",
      "archived": "보관",
      "shipped": "완료"
    }
  },
  "research": {
    "empty": {
      "description": "곧 채웁니다.",
      "title": "아직 공개한 연구가 없습니다"
    },
    "kind": {
      "lab": "연구실",
      "paper": "논문",
      "rne": "R&E"
    },
    "links": {
      "paper": "논문",
      "poster": "포스터",
      "repo": "저장소",
      "site": "링크"
    },
    "page": {
      "description": "학교와 연구실에서 한 것들.",
      "title": "연구"
    },
    "period": {
      "ongoing": "현재"
    }
  },
  "resume": {
    "awards": {
      "project": "관련 프로젝트",
      "title": "대회"
    },
    "career": {
      "empty": "아직 채우지 않았습니다",
      "title": "이력"
    },
    "download": {
      "label": "PDF로 저장"
    },
    "education": {
      "title": "학력"
    },
    "experience": {
      "title": "경력"
    },
    "page": {
      "description": "PDF로 들고 갈 수 있는 이력서입니다.",
      "title": "이력서"
    },
    "period": {
      "ongoing": "현재"
    },
    "projects": {
      "title": "주요 프로젝트"
    },
    "skills": {
      "title": "기술"
    }
  }
}
