// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "blog": {
    "detail": {
      "back": "글 목록"
    },
    "empty": {
      "description": "곧 채웁니다.",
      "title": "아직 쓴 글이 없습니다"
    },
    "item": {
      "writtenIn": "작성 언어"
    },
    "page": {
      "title": "글"
    }
  },
  "common": {
    "actions": {
      "permalink": "이 절 링크",
      "switchLanguage": "언어 변경"
    },
    "footer": {
      "email": "이메일"
    },
    "language": {
      "available": "이 페이지는 {{name}}로도 볼 수 있습니다.",
      "dismiss": "닫기",
      "view": "{{name}}로 보기"
    },
    "nav": {
      "blog": "글",
      "career": "이력",
      "home": "홈",
      "label": "주요 메뉴",
      "menu": "메뉴",
      "projects": "프로젝트",
      "research": "연구",
      "resume": "이력서"
    },
    "notFound": {
      "action": "홈으로",
      "description": "주소를 다시 확인해 주세요.",
      "title": "페이지를 찾을 수 없습니다"
    },
    "site": {
      "bio": ["안녕하세요, 류현승입니다. 과학영재학교 광주과학고등학교를 졸업하고, 현재 GIST에서 EECS와 AI를 복수전공하고 있습니다. 수학과 물리학, 천문학을 비롯한 이론적 과학 전반에 흥미를 느끼며, 특히 세상을 설명하는 법칙이 컴퓨터라는 이산적인 세계 속에서도 똑같이 작동하는 순간에서 가장 큰 아름다움을 발견합니다. 흥미로운 개념을 공부해 온전히 체화한 뒤, 이를 시뮬레이션으로 풀어내는 과정이 제가 가장 사랑하는 일입니다.", "대학 입학 후로는 이전까지 다뤄본 적 없던 프론트엔드와 백엔드, 앱 개발과 디자인을 새로 익혀 어느 정도 다룰 수 있는 사람이 되었습니다. 그 과정에서 코드와 디자인이 실제로 누군가에게 도움이 되는 결과물로 이어질 때의 성취감을 알게 되었고, 이는 제게 새로운 방향의 동기가 되었습니다.", "저는 하나의 개념에 꽂히면 질릴 때까지 파고드는 사람입니다. 그렇게 얻은 것을 스스로의 손으로 다시 만들어봐야 비로소 제 것이 되었다고 느낍니다. 연구든 공부든 개발이든 디자인이든 이 태도는 변하지 않으며, 이것이 저를 계속 앞으로 나아가게 하는 힘입니다. 그 힘으로 만든 작품이 언젠가 누군가의 일상에 스며들어 작은 영감이 되고, 나아가 긍정적인 변화로 이어지는 순간을 꿈꿉니다."],
      "description": "류현승의 포트폴리오",
      "location": "대한민국",
      "name": "류현승",
      "roles": ["오픈소스 기여자", "풀스택 개발자", "CS/AI 연구자", "디자인 엔지니어"]
    },
    "theme": {
      "dark": "어둡게",
      "label": "테마: {{mode}}",
      "light": "밝게",
      "system": "시스템 설정"
    }
  },
  "home": {
    "contributions": {
      "day": "{{date}}에 {{count, number}}회 기여",
      "less": "적음",
      "more": "많음",
      "total": "지난 1년간 {{value, number}}회 기여"
    },
    "entries": {
      "label": "바로가기"
    },
    "footer": {
      "updated": "최종 업데이트"
    },
    "sections": {
      "about": "소개",
      "contributions": "활동"
    }
  },
  "projects": {
    "detail": {
      "back": "프로젝트 목록"
    },
    "empty": {
      "description": "다른 기술이나 검색어로 찾아보세요.",
      "title": "해당하는 프로젝트가 없습니다"
    },
    "filter": {
      "reset": "필터 초기화",
      "results": "{{count}}개"
    },
    "links": {
      "demo": "데모",
      "package": "패키지",
      "paper": "논문",
      "post": "관련 글",
      "repo": "저장소"
    },
    "page": {
      "title": "프로젝트"
    },
    "period": {
      "ongoing": "현재"
    },
    "search": {
      "clear": "검색어 삭제",
      "label": "프로젝트 검색",
      "placeholder": "제목·설명·기술로 검색"
    },
    "status": {
      "active": "진행 중",
      "archived": "보관",
      "shipped": "완료"
    }
  },
  "research": {
    "detail": {
      "back": "연구 목록",
      "bibtex": "BibTeX 복사",
      "copied": "복사했습니다",
      "references": "참고문헌"
    },
    "empty": {
      "description": "곧 채웁니다.",
      "title": "아직 공개한 연구가 없습니다"
    },
    "kind": {
      "lab": "연구실",
      "paper": "논문",
      "rne": "R&E"
    },
    "links": {
      "paper": "논문",
      "poster": "포스터",
      "repo": "저장소",
      "site": "링크"
    },
    "page": {
      "title": "연구"
    },
    "period": {
      "ongoing": "현재"
    }
  },
  "resume": {
    "awards": {
      "title": "대회"
    },
    "career": {
      "empty": "아직 채우지 않았습니다",
      "title": "이력"
    },
    "download": {
      "label": "PDF로 저장"
    },
    "education": {
      "title": "학력"
    },
    "experience": {
      "title": "경력"
    },
    "page": {
      "title": "이력서"
    },
    "period": {
      "ongoing": "현재"
    },
    "projects": {
      "title": "주요 프로젝트"
    },
    "skills": {
      "title": "기술"
    }
  }
}
