// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "about": {
    "awards": {
      "title": "수상"
    },
    "download": {
      "label": "PDF로 저장"
    },
    "education": {
      "title": "학력"
    },
    "experience": {
      "title": "경력"
    },
    "projects": {
      "title": "주요 프로젝트"
    },
    "skills": {
      "title": "기술"
    }
  },
  "blog": {
    "detail": {
      "back": "글 목록"
    },
    "empty": {
      "description": "곧 채웁니다.",
      "title": "아직 쓴 글이 없습니다"
    },
    "item": {
      "writtenIn": "글이 쓰인 언어"
    },
    "page": {
      "description": "요즘 파고 있는 것들. 글은 쓴 언어 그대로 둡니다.",
      "title": "글"
    }
  },
  "common": {
    "actions": {
      "switchLanguage": "언어 바꾸기",
      "toggleTheme": "테마 바꾸기"
    },
    "app": {
      "name": "rhseung"
    },
    "nav": {
      "about": "소개",
      "blog": "글",
      "label": "주요 메뉴",
      "projects": "프로젝트"
    },
    "notFound": {
      "action": "홈으로",
      "description": "주소를 다시 확인해 주세요.",
      "title": "페이지를 찾을 수 없습니다"
    }
  },
  "home": {
    "hero": {
      "projects": "프로젝트 보기"
    },
    "sections": {
      "about": "더 자세히 →",
      "posts": "최근 글",
      "projects": "골라둔 것"
    }
  },
  "projects": {
    "detail": {
      "back": "프로젝트 목록"
    },
    "domain": {
      "backend": "백엔드",
      "graphics": "그래픽스",
      "systems": "시스템",
      "web": "웹"
    },
    "empty": {
      "description": "다른 분야를 골라보세요.",
      "title": "해당하는 프로젝트가 없습니다"
    },
    "filter": {
      "all": "전체",
      "label": "분야로 좁히기"
    },
    "links": {
      "demo": "데모",
      "paper": "논문",
      "post": "관련 글",
      "repo": "저장소"
    },
    "page": {
      "description": "직접 만든 것들. 분야로 좁혀서 볼 수 있습니다.",
      "title": "프로젝트"
    },
    "period": {
      "ongoing": "현재"
    },
    "status": {
      "active": "진행 중",
      "archived": "보관",
      "shipped": "완료"
    }
  }
}
